routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
#Admin login
Route::get('admin', 'Auth\LoginController@redirectAdminLogin');

Route::get('/admin/login', 'Auth\LoginController@showLoginAdminForm')->name('admin.login');
Route::post('/admin/login', 'Auth\LoginController@loginAdmin')->name('post.admin.login');
Route::post('/admin/logout', 'Auth\LoginController@logoutAdmin')->name('admin.logout');
Route::group(['prefix' => 'admin', 'middleware' => 'authAdmin'], function () {
  #Dashboard
  Route::get('/dashboard', 'Auth\LoginController@dashboard')->name('admin.dashboard');

  #Program
  Route::get('/programs', 'Admin\ProgramController@index')->name('admin.program.index');
  Route::get('/datatable/get-program', 'Admin\ProgramController@getPrograms')->name('datatable.programs');
  Route::get('/programs/{id}/show', 'Admin\ProgramController@show')->name('admin.program.show');
  Route::get('/programs/new', 'Admin\ProgramController@create')->name('admin.program.create');
  Route::post('/programs', 'Admin\ProgramController@store')->name('admin.programs.store');
  Route::get('/programs/{id}/edit', 'Admin\ProgramController@edit')->name('admin.programs.edit');
  Route::put('/programs/{id}', 'Admin\ProgramController@update')->name('admin.programs.update');

  #User
  Route::group(['prefix' => 'users', 'namespace' => 'Admin'], function() {
    Route::get('/', 'UserController@index')->name('admin.user.list');
    Route::get('new', 'UserController@create')->name('admin.user.create');
    Route::post('/', 'UserController@store')->name('admin.user.store');
    Route::get('{id}', 'UserController@show')->name('admin.user.show');
  });

  # Supporter
  Route::group(['prefix' => 'supporters', 'namespace' => 'Admin'], function() {
    Route::get('/', 'SupporterController@index')->name('admin.supporter.list');
    Route::get('new', 'SupporterController@create')->name('admin.supporter.create');
    Route::post('/', 'SupporterController@store')->name('admin.supporter.store');
    Route::get('{id}', 'SupporterController@show')->name('admin.supporter.show');
    Route::get('{id}/edit', 'SupporterController@edit')->name('admin.supporter.edit');
    Route::put('{id}', 'SupporterController@update')->name('admin.supporter.update');
  });

  #Club
  Route::get('/clubs', 'Admin\ClubController@show')->name('admin.club.show');
  Route::get('/clubs/{id}', 'Admin\ClubController@detail')->name('admin.club.detail');

  # Club join user
  Route::get('club_join_users', 'Admin\ClubJoinUserController@index')->name('admin.club_join_user.list');

});

#Authenticate
Route::get('/login', 'Auth\LoginController@showLoginForm');
Route::post('/login', 'Auth\LoginController@login')->name('login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
Route::get('/login_from_email', 'Auth\LoginController@loginFromEmail');

#Publish post
Route::get('posts/{id}', 'PostController@show')->name('posts.show');

Route::group(['middleware' => 'auth'], function () {
  # Recommend Programs
  Route::group(['middleware' => 'userable'], function() {
      Route::get('recommend_programs', 'ProgramController@recommend')->name('recommend');
      Route::post('recommend_programs/join', 'ProgramController@join')->name('recommend_programs.join');
  });

  Route::group(['middleware' => 'checkAgreementFlag', 'prefix' => 'tutorial'], function() {
    Route::get('/', 'TutorialController@nickname')->name('tutorial');
    Route::post('nickname', 'TutorialController@postNickname')->name('tutorial.nickname.post');
    Route::get('height_weight', 'TutorialController@heightWeight')->name('tutorial.height_weight');
    Route::post('height_weight', 'TutorialController@postHeightWeight')->name('tutorial.height_weight.post');
    Route::get('gender', 'TutorialController@gender')->name('tutorial.gender');;
    Route::post('gender', 'TutorialController@postGender')->name('tutorial.gender.post');
    Route::get('birthday', 'TutorialController@birthday')->name('tutorial.birthday');
    Route::post('birthday', 'TutorialController@postBirthday')->name('tutorial.birthday.post');
    Route::get('plan', 'TutorialController@plan')->name('tutorial.plan');
    Route::post('plan', 'TutorialController@postPlan')->name('tutorial.plan.post');
    Route::get('goal', 'TutorialController@goal')->name('tutorial.goal');
    Route::post('goal', 'TutorialController@postGoal')->name('tutorial.goal.post');
    Route::get('confirm', 'TutorialController@confirm')->name('tutorial.confirm');
    Route::post('confirm', 'TutorialController@postData')->name('tutorial.confirm.post');
  });

  Route::post('user/profile', 'UserController@createProfile')->name('profile.create');
  Route::get('/profile', 'UserController@editProfile')->name('profile.show');
  Route::get('/profile/edit', 'UserController@editField')->name('profile.edit');
  Route::put('/profile', 'UserController@updateField')->name('profile.update');
  Route::put('/avatar', 'UserController@updateAvatar')->name('avatar.update');

  #Top
  Route::get('/', 'TopPageController@index')->name('toppage');
  Route::post('/ajax/agree_term', 'TopPageController@ajaxTopPage')->name('ajax.agree_term');

  #Terms of service
  Route::get('/terms_of_service', function () {
    return view('terms_of_service.show');
  });

  #My page
  Route::group(['middleware' => ['checkAgreementFlag', 'checkProfile']], function () {
    Route::get('/mypage', 'MyPageController@index')->name('mypage.index');
    Route::post('/ajax/daily_report', 'MyPageController@ajaxDailyReport')->name('ajax.daily_report');
    Route::post('/mypage/dialog/{id}/close', 'MyPageController@close')->name('mypage.close');
  });

  #Programs
  Route::get('/programs', 'ProgramController@list')->name('program.list');
  Route::get('/programs/{programId}{r?}', 'ProgramController@detail')->name('program.detail');
  Route::post('/ajax/update_user_join_club', 'ProgramController@updateUserJoinClub')->name('ajax.update_user_join_club');

  #Supporters
  Route::get('supporters', 'SupporterController@index')->name('supporters.list');
  Route::get('supporters/{id}', 'SupporterController@detail')->name('supporters.detail');
  Route::post('supporters/{id}/like', 'SupporterController@like')->name('supporters.like');
  Route::delete('supporters/{id}/like', 'SupporterController@unlike')->name('supporters.unlike');

  #Posts
  Route::post('posts/report/{id}', 'PostController@report');
  Route::delete('posts/report/{id}', 'PostController@deleteReport');
  Route::delete('posts/delete/{postId}', 'PostController@delete');
  Route::get('posts', 'PostController@create')->name('posts.create');
  Route::post('posts', 'PostController@store')->name('posts.store');
  Route::get('posts/edit/{id}', 'PostController@edit')->name('posts.edit');
  Route::put('posts/edit/{id}', 'PostController@update')->name('posts.update');

  #Comments
  Route::get('comments/{postId}', 'CommentController@show');
  Route::post('comments/create/{postId}', 'CommentController@create');
  Route::delete('comments/delete/{commentId}', 'CommentController@delete');
  Route::put('comments/edit/{commentId}', 'CommentController@edit');

  #Post Like
  Route::get('/post-likes/{postId}', 'LikeController@showUsersLikedPost');
  Route::post('like/posts/{postId}', 'LikeController@likePost');
  Route::delete('like/posts/{postId}', 'LikeController@deleteLikePost');

  #Comment Like
  Route::get('/comment-likes/{commentId}', 'LikeController@showUsersLikedConmment');
  Route::post('like/comments/{commentId}', 'LikeController@likeComment');
  Route::delete('like/comments/{commentId}', 'LikeController@deleteLikeComment');

  #Supporter Like
  Route::get('/supporter-likes/{supporterId}', 'LikeController@showUsersLikedSupporter');

  #User weigth
  Route::get('report-weight/{doneReportId}', 'WeightReportController@index');
  Route::post('report-weight/{doneReportId}', 'WeightReportController@create');
  Route::get('weight', 'UserController@weightGraph')->name('weight.index');
  Route::post('weight/update', 'WeightReportController@createWeightWithoutDoneReportUser');

  #Notifications
  Route::get('/notifications', 'NotificationController@index');
  Route::post('/notifications/read/{id}', 'NotificationController@updateReadAt');

  #Communications
  Route::get('communications/{clubId}', 'CommunicationController@show')->name('communications.list');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Club;
use DB;
use Log;

class Post extends Model
{
    const FAIL_STATUS = 0;
    const SUCCESS_STATUS = 1;

    protected $table = 'posts';
    protected $fillable = ['club_id', 'user_id', 'text'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function club()
    {
        return $this->belongsTo('App\Models\Club');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }

    public function images()
    {
        return $this->hasMany('App\Models\PostImage');
    }

    public function userLikes()
    {
        return $this->belongsToMany('App\User', 'like_posts', 'post_id', 'user_id')
                    ->withPivot('user_id', 'post_id');
    }

    public function doneReports()
    {
        return $this->hasMany('App\Models\DoneReport');
    }

    public static function getPostByClubId($clubId)
    {
        return self::withCount('comments', 'userLikes')
                    ->leftJoin('done_reports as dr', 'posts.id', '=', 'dr.post_id')
                    ->where('club_id', $clubId)
                    ->orderByRaw('SUBSTR(posts.created_at, 1, 10) DESC')
                    ->orderBy('dr.date', 'DESC')
                    ->orderBy('id', 'DESC');
    }

    public static function deleteRecord($userId, $postId)
    {
        $post = Post::find($postId);
        if ($post->user->id !== $userId) {
            Log::warning('Permission denied for deletion: ' . json_encode([
                'user_id' => $userId,
                'post_id' => $postId
            ]));
            return self::FAIL_STATUS;
        }
        try {
            $post->delete();
        } catch (\Exception $e) {
            return self::FAIL_STATUS;
        }
        return self::SUCCESS_STATUS;
    }

    public static function checkUniqueDoneReportCurrentDate($clubId)
    {
        $post = self::where('club_id', $clubId)->whereHas('doneReports', function($query) {
            $query->orderBy('id', 'DESC')->whereDate('date', date('Y-m-d'));
        })->first();
        if (!empty($post->doneReports) && $post->doneReports->count() > 0) {
            return false;
        }
        return true;
    }

    public static function createPostBySupporter($clubId)
    {
        $club = Club::find($clubId);
        $userIdOfSupporter = $club->program->supporter->user->id;
        $newPost= Post::create([
            'club_id' => $clubId,
            'user_id' => $userIdOfSupporter,
            'text' => config('post.automaticly.text')
        ]);
        return $newPost->id;
    }
}

app/Http/Controllers/CommunicationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Club;
use App\Models\ClubJoinUser;
use App\User;
use Auth;
use Log;

class CommunicationController extends Controller
{
    const PER_PAGE = 10;

    public function show($clubId)
    {
        $club = Club::find($clubId);
        if (empty($club) || (!$club->isJoin(Auth::user()->id) && !User::isOwnClub(Auth::user()->id, $clubId))) {
            if (empty($club)) {
                Log::warning('Not Found: ' . json_encode(['club_id' => $clubId]));
            } else {
                Log::warning('Permission denied: ' . json_encode([
                    'club_id' => $clubId,
                    'user_id' => Auth::user()->id
                ]));
            }
            abort(404);
        }
        $posts = Post::getPostByClubId($clubId)->paginate(self::PER_PAGE);
        $userWeight = ClubJoinUser::getUserWeightByCurrentDate($clubId);
        $userWeight = empty($userWeight) ? 0 : $userWeight;
        foreach ($posts as &$post) {
            if($post->doneReports->count() > 0) {
                $post->doneReportId = $post->doneReports->first()->id;
                $countDoneReportUsers = count($post->doneReports->first()->doneReportUsers);
                $post->countDoneReportUsers = $club->program->done_report_type==1 ? $countDoneReportUsers : $userWeight;
                $post->isDoneReport = ClubJoinUser::isUserDoneReport(Auth::user()->id, $post->id);
            }
        }
        return view("communication.show")->with([
            'posts' => $posts,
            'club' => $club,
            'joinUserCount' => count($club->joinUsers()),
        ]);
    }
}

resources/views/communication/_post.blade.php
  <div class="col-sm-12 box" id="post-{{ $post->id }}">
    <div class="row">
      <div class="col-xs-2">
        <img src="{{ $post->user->profile->getPhotoImage() }}" alt="" class="img-responsive img-circle">
      </div>
      <div class="col-xs-8 text-left">
        <b>{{ $post->user->profile->nickname }}</b>
        <p>{{ $post->created_at }}</p>
      </div>

      {{-- Popup Menu --}}
      <div class="col-xs-2">
        @if (Auth::user()->id == $post->user->id)
          <div class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-ellipsis-h pull-right"></i></a>
            <ul class="dropdown-menu" style="left: -125px!important">
              <li><a href="#" onclick="return removePost({{ $post->id }})"><i class="fa fa-trash"></i>  この投稿を削除する</a></li>
              <div class="dropdown-divider"></div>
              <li><a href="{{ route('posts.edit', $post->id) }}"><i class="fa fa-edit"></i>  この投稿を編集する</a></li>
              <div class="dropdown-divider"></div>
              <li><a href="#" onclick="shareSns({{ $post->id }})"><i class="fa fa-share-alt"></i>  この投稿をシェアする</a></li>
            </ul>
          </div>
        @endif
      </div>

      <div class="col-xs-12">
        <p>{{ $post->text }}</p>
      </div>

      @foreach($post->images as $image)
        <div class="col-xs-4">
          <img src="{{ url($image->image_url) }}" alt="" class="img-responsive">
        </div>
      @endforeach

      <div class="col-xs-12">
        @if ($post->userLikes->contains('pivot.user_id', Auth::user()->id))
          <p data-id="{{ $post->id }}" onclick="deleteLike({{ $post->id }})" class="fa fa-heart text-pink like-icon"></p>
        @else
          <p data-id="{{ $post->id }}" onclick="like({{ $post->id }})" class="fa fa-heart-o like-icon"></p>
        @endif
        <span class="like" data-id="{{ $post->id }}" onclick="likePage({{ $post->id }})">{{ $post->user_likes_count }} @lang('button.like')</span>
        &nbsp; &nbsp; &nbsp; &nbsp;
        <span onclick="clickComment({{ $post->id }})" class="comment-icon"><p class="fa fa-comment-o"></p> {{ $post->comments_count }} @lang('button.comments')</span>
      </div>
    </div>
  </div>

resources/views/communication/_postReport.blade.php
    <div class="col-sm-12 box">
      <div class="row" id="report_{{ $postReport->doneReportId }}">
        <div class="col-xs-2">
          <img src="{{ $postReport->user->profile->getPhotoImage() }}" alt="" class="img-responsive img-circle">
        </div>
        <div class="col-xs-8 text-left">
          <b>{{ $postReport->user->profile->nickname }}</b>
          <p>{{ substr($postReport->created_at, 0, 10) }}</p>
        </div>

        <div class="col-xs-12">
          <p>{{ $postReport->text }}</p>
        </div>
        <div class="col-xs-12">
          <p class="pull-left">@lang('communication.progress_program')</p>
          <p class="pull-right ratio">{{ $postReport->countDoneReportUsers }} / {{ $joinUserCount }}</p>
        </div>
        <div class="col-xs-12">
          <div class="progress">
            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: {{ 100 * $postReport->countDoneReportUsers/$joinUserCount }}%"></div>
          </div>
        </div>
        <div class="col-xs-12">
          {{-- check post repo.navbar-default rt by supporter --}}
          @if (empty(Auth::user()->supporter))

            {{-- check this user already reported --}}
            @if ($postReport->isDoneReport)
              <p data-id="{{ $postReport->doneReportId }}" onclick="deleteReport({{ $club->program->done_report_type }}, {{ $postReport->doneReportId }})" class="fa fa-lock text-info report-icon"></p>
              <span class="report" data-id="{{ $postReport->doneReportId }}">{{ $postReport->countDoneReportUsers }}</span>
              <span class="report-status"> @lang('button.reported')</span>
            @else
              <p data-id="{{ $postReport->doneReportId }}" onclick="report({{ $club->program->done_report_type }}, {{ $postReport->doneReportId }})" class="fa fa-lock report-icon"></p>
              <span class="report" data-id="{{ $postReport->doneReportId }}">{{ $postReport->countDoneReportUsers }}</span> <span class="report-status">@lang('button.done')</span>
            @endif
            &nbsp; &nbsp; &nbsp; &nbsp;
          @endif
          @if ($postReport->userLikes->contains('pivot.user_id', Auth::user()->id))
            <p data-id="{{ $postReport->id }}" onclick="deleteLike({{ $postReport->id }})" class="fa fa-heart text-pink like-icon"></p>
          @else
            <p data-id="{{ $postReport->id }}" onclick="like({{ $postReport->id }})" class="fa fa-heart-o like-icon"></p>
          @endif
          <span class="like" data-id="{{ $postReport->id }}" onclick="likePage({{ $postReport->id }})">{{ $postReport->userLikes->count() }} @lang('button.like')</span>
          &nbsp; &nbsp; &nbsp; &nbsp;
          <span onclick="clickComment({{ $postReport->id }})" class="comment-icon"><p class="fa fa-comment-o"></p> {{ $postReport->comments->count() }} @lang('button.comments')</span>
        </div>

      </div>
    </div>

resources/views/communication/show.blade.php
@extends('layouts.app', ['title' => $club->program->title, 'back_url' => '/mypage' ])

@section('content')
<div class="container">
  @if (session('success'))
    <span class="col-xs-12 alert alert-success">
      <strong>{{ session('success') }}</strong>
    </span>
  @elseif (session('error'))
    <span class="col-xs-12 alert alert-danger">
      <strong>{{ session('error') }}</strong>
    </span>
  @endif


  {{-- Post --}}

  <div class="col-sm-12 box">
    <div class="row">
      <div class="col-xs-2">
        <img src="{{ Auth::user()->profile->getPhotoImage() }}" alt="" class="img-responsive img-circle">
      </div>
      <div class="col-xs-10">
        <input type="text" placeholder="@lang('communication.how_do_you_feel')" class="form-control" id="input-post"/>
      </div>
    </div>
  </div>

  {{-- Posts --}}

  @foreach ($posts as $post)
    @if ($post->doneReports->count() > 0)
    		{{-- Post of report --}}
    		@component('communication._postReport', [
               'postReport' => $post,
               'joinUserCount' => $joinUserCount,
               'club' => $club
            ])
        @endcomponent
    @else
    		@component('communication._post', ['post'=>$post]) @endcomponent
    @endif
  @endforeach

  {{ $posts->links() }}

</div>
@endsection

@section('style')

<style type="text/css" media="screen">

  .box {
    background: #FFF;
    padding: 8px;
    border: solid 1px #CCC;
    margin-bottom: 16px;
  }
  .like-icon, .comment-icon, .report-icon, .like, .report-type {
    cursor: pointer;
  }
</style>
@endsection

@section('script')
<script>
  function shareSns(id)
  {
    var domain = "{{ env('APP_URL') }}";
    var url = domain + '/posts/' + id;
    var fbpopup = window.open("https://www.facebook.com/sharer/sharer.php?u=" + url, "pop", "width=600, height=400, scrollbars=no");
    return false;
  }
  function clickComment($postId) {
    window.location = "/comments/" + $postId;
  }
  function likePage(postId) {
    window.location = "/post-likes/" + postId;
  }
  $("#input-post").click(function() {
    $(this).attr('disabled', 'disabled');
    window.location = '/posts/?club_id=' + {{ $club->id }};
  });

  function like(postId) {
    $(".like-icon[data-id='"+ postId +"']").css("pointer-events", "none");
    var countLike = $(".like[data-id='"+ postId +"']").text();
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $.ajax({
      url: '/like/posts/' + postId,
      type: 'POST',
      dataType: 'JSON',
    })
    .done(function(res) {
      $('.like-icon').css("pointer-events", 'auto');
      if (res.status == 1) {
        $(".like-icon[data-id='"+ postId +"']").removeClass('fa-heart-o').addClass('text-pink').addClass('fa-heart').attr('onclick', "deleteLike("+ postId +")");
        $(".like[data-id='"+ postId +"']").text(parseInt(countLike) + 1 + ' Like');
      }
    })
  }

  function deleteLike(postId) {
    $(".like-icon[data-id='"+ postId +"']").css("pointer-events", "none");
    var countLike = $(".like[data-id='"+ postId +"']").text();
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $.ajax({
      url: '/like/posts/' + postId,
      type: 'DELETE',
      dataType: 'JSON',
    })
    .done(function(res) {
      $('.like-icon').css("pointer-events", 'auto');
      if (res.status == 1) {
        $(".like-icon[data-id='"+ postId +"']").removeClass('fa-heart').removeClass('text-pink').addClass('fa-heart-o').attr('onclick', "like("+ postId +")");
        $(".like[data-id='"+ postId +"']").text(parseInt(countLike) - 1 + ' Like');
      }
    })
  }

  function removePost(postId)
  {
    if (confirm('{{ trans('message.sure_delete') }}')) {
      $.ajaxSetup({
        headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
      });
      $.ajax({
        url: '/posts/delete/' + postId,
        type: 'DELETE',
        dataType: 'JSON',
      })
      .done(function(res) {
        if (res.status == 1) {
          $('#post-' + postId).remove();
        }
      })
    }
    return false;
  }

  function report(reportType, doneReportId) {
    if (reportType == 2) {
      window.location = '/report-weight/' + doneReportId;
      return;
    }
	var container = $("#report_"+doneReportId);
	container.find(".report-icon").css("pointer-events", "none");
    var countReport = container.find(".report").text();
    var total = {{ $joinUserCount }};
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $.ajax({
      url: '/posts/report/' + doneReportId,
      type: 'POST',
      dataType: 'JSON',
    })
    .done(function(res) {
        container.find(".report-icon").css("pointer-events", "auto");
        if (res.status) {
            container.find(".report-icon").addClass("text-info").attr("onclick", "deleteReport("+ doneReportId +")");
            container.find(".report").text(parseInt(countReport) + 1);
            container.find(".progress-bar").css("width", 100*(parseInt(countReport) + 1)/total + "%");
            container.find(".ratio").text(parseInt(countReport) + 1 + "/" + total);
            container.find(".report-status").text("Reported");
        }
    })
  }

  function deleteReport(reportType, doneReportId) {
    if (reportType == 2) {
        return;
    }
    var container = $("#report_"+doneReportId);
    container.find(".report-icon").css("pointer-events", "none");
    var countReport = container.find(".report").text();
    var total = {{ $joinUserCount }};
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $.ajax({
      url: '/posts/report/' + doneReportId,
      type: 'DELETE',
      dataType: 'JSON',
    })
    .done(function(res) {
        container.find(".report-icon").css("pointer-events", "auto");
        if (res.status) {
        		container.find(".report-icon").removeClass("text-info").attr("onclick", "report("+ doneReportId +")");
        		container.find(".report").text(parseInt(countReport) - 1);
        		container.find(".progress-bar").css("width", 100*(parseInt(countReport) - 1)/total + "%");
        		container.find(".ratio").text(parseInt(countReport) - 1 + "/" + total);
        		container.find(".report-status").text("Done");
        }
    })
  }
</script>
@endsection